# Generated by Django 6.0 on 2025-12-19 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marathons", "0001_initial"),
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marathon",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curated_marathons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marathon",
            name="movies",
            field=models.ManyToManyField(to="movies.movie"),
        ),
        migrations.AddField(
            model_name="marathon",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_marathons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marathonticket",
            name="marathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="marathons.marathon",
            ),
        ),
        migrations.AddField(
            model_name="marathonticket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marathon_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
