# Generated by Django 6.0 on 2025-12-22 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marathons", "0002_initial"),
        ("movies", "0005_alter_movie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marathon",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="marathon",
            name="movies",
            field=models.ManyToManyField(blank=True, to="movies.movie"),
        ),
        migrations.AlterField(
            model_name="marathon",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="marathon",
            name="total_duration",
            field=models.IntegerField(default=0),
        ),
    ]
