# Generated by Django 6.0 on 2026-01-03 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marathons", "0003_alter_marathon_description_alter_marathon_movies_and_more"),
        ("movies", "0005_alter_movie_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="marathon",
            name="movies",
            field=models.ManyToManyField(to="movies.movie"),
        ),
        migrations.AlterField(
            model_name="marathon",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="marathon",
            name="total_duration",
            field=models.PositiveIntegerField(help_text="Total duration in minutes"),
        ),
        migrations.AddConstraint(
            model_name="marathon",
            constraint=models.UniqueConstraint(
                fields=("title", "start_date"), name="unique_marathon_title_start_date"
            ),
        ),
    ]
