# Generated by Django 6.0 on 2025-12-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="value",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
