# Generated by Django 6.0 on 2025-12-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-title"]},
        ),
    ]
