# Generated by Django 6.0 on 2026-01-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="movies.movie",
            ),
        ),
    ]
